### ISSUE TITLE
BUG - easygpu_lyon examples crash when resizing window

### ISSUE THREAD

**Issue by zurrty** [khonsulabs/easygpu#4]
The examples in the easygpu_lyon crate crash when resizing the window. The window is also completely transparent and does not display any of the expected shapes. It seems that the multisample texture isn't being resized along with the render surface, which is what causes the crash. Running the example with the multisample texture removed seems to fix the crash, though there is still nothing shown on the window.

Crash message after resizing window:
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 10, Gl)>`
    In a pass parameter
      note: command buffer = `<CommandBuffer-(0, 10, Gl)>`
    attachments have differing sizes: ("depth", Extent3d { width: 612, height: 600, depth_or_array_layers: 1 }) is followed by ("color", Extent3d { width: 800, height: 600, depth_or_array_layers: 1 })

', /home/zurrty/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.15.1/src/backend/direct.rs:3024:5
```

System specs (`inxi -CG` output):
```txt
CPU:
  Info: 12-core (4-mt/8-st) model: 12th Gen Intel Core i7-1260P bits: 64
    type: MST AMCP cache: L2: 9 MiB
  Speed (MHz): avg: 2063 min/max: 400/4700:3400 cores: 1: 1033 2: 2500
    3: 1275 4: 1025 5: 921 6: 2500 7: 2500 8: 2500 9: 2500 10: 1087 11: 2837
    12: 1716 13: 2636 14: 1753 15: 2960 16: 3280
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics driver: i915 v: kernel
  Device-2: NVIDIA GA104 [GeForce RTX 3070 Lite Hash Rate] driver: nvidia
    v: 520.56.06
  Display: wayland server: X.org v: 1.21.1.7 with: Xwayland v: 22.1.8
    compositor: kwin_wayland driver: X: loaded: intel dri: i965 gpu: i915,nvidia
    resolution: 1: 1920x1080 2: 2256x1504
  API: OpenGL v: 4.6 Mesa 23.0.0 renderer: Mesa Intel Graphics (ADL GT2)
```

**Comment by ecton** [comment]
Thank you for reporting this. I can see how this could be confusing -- I was expecting these examples to show the most minimal usage, and for users to mostly need to still understand how `wgpu` and `winit` work together by following [the wgpu examples](https://github.com/gfx-rs/wgpu/blob/master/wgpu/examples/hello-triangle/main.rs#L93-L102).

Since `easygpu` wraps the surface inside of `Renderer`, the `configure()` call is available on `Renderer` to update the surface before calling `current_frame()`.

I'll update the examples to include the resize handling code to prevent the crash.

**Comment by ecton** [comment]
Oops, my bad -- my memory of that code was a lot different than I remembered. You were absolutely right. I've updated the sandbox for the examples.
